import json
import os
import random

def convert_json_to_target_format(input_file, output_file):
    # Prepare an empty list to store the converted data
    json_list = []

    # Open the JSON file and read its contents
    with open(input_file, 'r') as file:
        data = json.load(file)
        for item in data["hh-rlhf"]:
            if item["result"]["orig"]["prediction"] == 1:
                output = "Output (a)"
            elif item["result"]["orig"]["prediction"] == 2:
                output = "Output (b)"
            else:
                raise ValueError("Invalid label!")
            # Randomly swap the outputs
            if random.choice([True, False]):
                if output == "Output (a)":
                    output = "Output (b)"
                elif output == "Output (b)":
                    output = "Output (a)"
                item["response1"], item["response2"] = item["response2"], item["response1"]
            json_object = {
                "instruction": f"""Select the Output (a) or Output (b) that is better for the given instruction. The two outputs are generated by two different AI chatbots respectively.

Here are some rules of the evaluation:
(1) You should prioritize evaluating whether the output honestly/precisely/closely executes the instruction, then consider its helpfulness, accuracy, level of detail, harmlessness, etc.
(2) Outputs should NOT contain more/less than what the instruction asks for, as such outputs do NOT precisely execute the instruction.
(3) You should avoid any potential bias and your judgment should be as objective as possible. For example, the order in which the outputs were presented should NOT affect your judgment, as Output (a) and Output (b) are **equally likely** to be the better.

Do NOT provide any explanation for your choice.
Do NOT say both / neither are good.
You should answer using ONLY "Output (a)" or "Output (b)". Do NOT output any other words.

# Instruction:
{item["instruction"]}

# Output (a):
{item["response1"]}

# Output (b):
{item["response2"]}

# Which is better, Output (a) or Output (b)? Your response should be either "Output (a)" or "Output (b)":""",
                    "input": "",

                    "system": "You are a helpful assistant in evaluating the quality of the outputs for a given instruction. Your goal is to select the best output for the given instruction.",
                    "output": output
                }
            # Append the converted data to the list
            json_list.append(json_object)

    output_dir = os.path.dirname(output_file)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir) 
    # Write the converted data to the output file in JSON format
    with open(output_file, 'w') as file:
        json.dump(json_list, file, indent=4)


input_file_path = '../result/Llama-3.2-3B-Instruct-hh-rlhf_et_lr_1e-5_epoch_3/hh-rlhf.json'
output_file_path = '../data/hh-rlhf_et_llama.json'

convert_json_to_target_format(input_file_path, output_file_path)

print("Over!")
